ktor:
    application:
        modules:
            - com.fortedigital.ApplicationKt.module
    deployment:
        port: 8080
kafka:
    bootstrap-servers: 'kafka-0:19092'

database:
    embedded: false
    host: localhost
    port: 5432
    databaseName: 'kafka'
    user: 'kafka'
    password: 'kafka'
